name: ml_api
channels:
  - conda-forge
  - conda

dependencies:
  - python=3.9
  - scikit-learn==0.24.2
  - pandas==1.2.4
  - pydantic==1.8.2
  - pytest==6.2.3
  - requests==2.25.1
  - typer==0.3.2
  - pip:
    - fastapi==0.65.1
    - uvicorn[standard]==0.13.4
