name: ml_api
channels:
  - conda-forge
  - conda

dependencies:
  - python=3.9
  - scikit-learn
  - xgboost==1.4.0
  - pandas==1.2.4
  - pydantic==1.8.2
  - pip:
    - fastapi==0.65.1
    - uvicorn[standard]==0.13.4
